### PR TITLE
Using ActiveJob for CatalogController#catalog_push

### PR DESCRIPTION
**Pull request by chinshr**
- Integrate ActiveJob
- Add working Dummy App for testing
- Rspec environment plus specs

### CODE REVIEW

**Comment by chinshr** [comment]
@schwartzdev please review when you have a free minute.

**Comment by schwartzdev** [comment]
I would caution against refactoring `catalog_controller.rb` because this will make it difficult to merge changes from the upstream repo. Also, under this new approach, the errors and warnings collected in `@diag` are lost. These need to be communicated back in the response to `CatalogController#catalog_push`. 

I would suggest rather than attempting to do all processing in one background task, finding subtasks like Image manipulation that can be safely processed in the background.

**Comment by chinshr** [comment]
Thanks for your feedback. I agree, making the entire call async is more difficult, but essentially the right thing to do. As you suggested, we could break the call up, but that is cumbersome and error prone, I will try using [delayed_paperclip](https://github.com/jrgifford/delayed_paperclip/).

BTW, I submitted the same pull request against the main repo asking for feedback from the current maintainer, @sorear, but haven't heard back. Do you have access to him/her?

Regarding the lack of producing error messages at the end of the controller call, here are some solutions I would like to discuss:
- RetailOps to provide us with a callback (API) that allows us to push the import errors after the batch call
- We could get smarter about import errors. i.e. collect errors on the spree side and pass them to operations (email, spree admin). 

Also spoke to @cdouglass and she showed me that the errors she gets back inside RetailOps are somewhat obscure, (hence, the value of having these errors inside RetailOps are minimal), or involve minor issues, like character set collisions, etc. So again, we could decide to communicate these errors differently to ops.

**Comment by cdouglass** [comment]
One minor issue with depending on the RO errors is that there's a "Retry" button but if the retry fails it does not generate a new error, so it's easy to get confused and think the product no longer has an issue even when nothing has been fixed.

**Comment by dnorman** [comment]
I am inclined to agree with @schwartzdev insofar as it makes sense to background-process only computationally intensive portions. This is because we rely on the in-band response for flow control, and event deduplication. 
With regard to error messaging, we are happy to make sensible refinements. It may make sense to improve error logging on the spree side, but as this module is used by others, it is most appropriate in our view to continue to convey error messages to the RetailOps alerts system. This is a powerful and necessary diagnostic tool.

With regard to the Retry button, it is my understanding that retry events simply go to the back of the queue, and are otherwise identical to the initial stimulus. As such, I believe they generate further retry-enabled error messages should they experience an error subsequently.

We will review your pull request within the next week and provide additional notes if necessary.

**Comment by cdouglass** [comment]
@dnorman I think your understanding is not accurate. Have you tested it? For the following example I am using product 9412, which has a "sku/permalink is already taken" error that cannot be resolved simply by retrying (an edit in Spree would be necessary). Let me know if there's anything I can do to make the retry/error message issue clearer.

Screenshot from 14:43 showing the original error message.
screen shot 2014-12-08 at 2 43 31 pm

At 14:58 I clicked the "retry" button for this error. To be sure I'd waited long enough, I edited another product, FRL0001, at 15:00 and saw that that edit had pushed through to Spree by 15:01. By 15:30 there was no still new error for product 9412, which would seem to indicate that the retry did not display a message for the error it must have encountered:
screen shot 2014-12-08 at 3 29 26 pm

At 15:31 I edited product 9412 to trigger a push. Shortly thereafter, an error message appeared timestamped 15:31, which would seem to indicate that the error message was triggered by my 15:31 push but not by the 14:58 retry.
screen shot 2014-12-08 at 3 36 56 pm

**Comment by chinshr** [comment]
@dnorman thanks for your feedback. If there was a retailops API callback endpoint we could easily reconciliate the error logs. Let me know if there exists one already?

FYI there are currently no specs, I got the test env configured, I could provide a separate pull request if you are interested?

**Pull request closed without merging**
