### PR TITLE
Automate refunds for partial cancellations

### PR DESCRIPTION
**Pull request by kknd113**

### CODE REVIEW

**Comment by kknd113** [comment]
@schwartzdev Can you take a brief look?

The reason why this is moved to retailops is because
a) We only want `order.contents.remove` call from retailops to issue automated refunds (e.g., we don't want to refund when spree user manually adjusts quantity from spree ui)

b) Flow never hits spree but only R.O for partial cancellations

@sankalpk

**Comment by schwartzdev** [comment]
Looks good.

**Comment by sankalpk** [comment]
:+1:

**Comment by kknd113** [comment]
cherry-picked

**Pull request closed without merging**
