### PR TITLE
- allows order controller to parse overidden LineItem#delivery_surcharge field.

### PR DESCRIPTION
**Pull request by quetzaluz**
@kknd113

### CODE REVIEW

**Comment by kknd113** [comment]
:+1:

**Comment by quetzaluz** [comment]
OK I'll only merge this after I finish testing the related spree PR

**Comment by schwartzdev** [comment]
:+1:  me too :shipit:

**Comment by quetzaluz** [comment]
cherry-picked f40d07134a1b8f2365c030743a56b34e13701882 and closing.

**Pull request closed without merging**
